# Generated by Django 4.1.7 on 2023-02-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="thumbnail",
            field=models.ImageField(
                default="class/default.png", upload_to="class/", verbose_name="강의 이미지"
            ),
        ),
    ]
