# Generated by Django 4.1.7 on 2023-03-01 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0002_alter_class_thumbnail"),
    ]

    operations = [
        migrations.AlterModelOptions(name="class", options={"ordering": ["-pk"]},),
    ]
