# Generated by Django 4.1.7 on 2023-03-01 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classes", "0003_alter_class_options"),
        ("users", "0002_alter_profile_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_title",
                    models.CharField(max_length=128, verbose_name="질문 제목"),
                ),
                ("question_text", models.TextField(verbose_name="질문 내용")),
                (
                    "register_dttm",
                    models.DateTimeField(auto_now_add=True, verbose_name="질문 등록 시간"),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.profile",
                        verbose_name="질문자 프로필",
                    ),
                ),
                (
                    "questioner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="질문자",
                    ),
                ),
                (
                    "related_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classes.class",
                        verbose_name="관련 수업",
                    ),
                ),
            ],
        ),
    ]
